# Generated by Django 5.2.5 on 2026-04-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['start'], 'verbose_name_plural': 'availabilities'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, help_text='Optional reason for visit.', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='note',
            field=models.CharField(blank=True, help_text='Optional note shown to patients.', max_length=120),
        ),
    ]
